# Generated by Django 6.0.2 on 2026-03-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deadline_type', models.CharField(choices=[('payment', 'Payment'), ('contract', 'Contract'), ('renewal', 'Renewal'), ('compliance', 'Compliance'), ('expiring_token', 'Expiring token/account'), ('product_milestone', 'Product milestone'), ('plan_milestone', 'Plan milestone'), ('other', 'Other')], default='other', max_length=30)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deadline',
                'verbose_name_plural': 'Deadlines',
                'db_table': 'deadlines_deadline',
                'ordering': ['due_date', 'title'],
            },
        ),
    ]
