# Generated by Django 6.0.2 on 2026-05-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0002_deadline_content_type_deadline_object_id'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='deadline_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('contract', 'Contract'), ('renewal', 'Renewal'), ('compliance', 'Compliance'), ('expiring_token', 'Expiring token/account'), ('rotation_due', 'Rotation due'), ('product_milestone', 'Product milestone'), ('plan_milestone', 'Plan milestone'), ('project_milestone', 'Project milestone'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
