# Generated by Django 6.0.2 on 2026-05-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='docs_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='homepage_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_kind',
            field=models.CharField(choices=[('saas', 'SaaS'), ('template_pack', 'Template pack'), ('ide', 'IDE'), ('design_tool', 'Design tool'), ('cloud_service', 'Cloud service'), ('asset_library', 'Asset library'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='commercial_products', to='topics.topic'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ProductLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('perpetual', 'Perpetual'), ('subscription', 'Subscription'), ('trial', 'Trial'), ('seat_based', 'Seat-based'), ('usage_based', 'Usage-based'), ('open_source', 'Open source')], default='subscription', max_length=20)),
                ('seats', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('ends_at', models.DateField(blank=True, null=True)),
                ('renewal_interval', models.CharField(choices=[('none', 'None'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='none', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], default='active', max_length=20)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('license_key_masked', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='products.product')),
            ],
            options={
                'verbose_name': 'Product license',
                'verbose_name_plural': 'Product licenses',
                'db_table': 'products_product_license',
                'ordering': ['product', '-ends_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_products', to='products.product')),
            ],
            options={
                'verbose_name': 'Project product',
                'verbose_name_plural': 'Project products',
                'db_table': 'products_project_product',
            },
        ),
    ]
