# Generated by Django 6.0.2 on 2026-05-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_status_product_docs_url_and_more'),
        ('projects', '0002_migrate_legacy_products_to_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproduct',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_products', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='projectproduct',
            unique_together={('project', 'product')},
        ),
    ]
