# Generated by Django 6.0.2 on 2026-05-26 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('milestones', '0001_initial'),
        ('plans', '0001_initial'),
        ('systems', '0001_initial'),
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('dev', 'Dev'), ('testing', 'Testing'), ('live', 'Live'), ('archived', 'Archived')], default='idea', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestones', models.ManyToManyField(blank=True, related_name='projects', to='milestones.milestone')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('plans', models.ManyToManyField(blank=True, related_name='projects', to='plans.plan')),
                ('systems', models.ManyToManyField(blank=True, related_name='projects', to='systems.system')),
                ('topics', models.ManyToManyField(blank=True, related_name='projects', to='topics.topic')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects_project',
                'ordering': ['name'],
            },
        ),
    ]
