# Generated by Django 6.0.2 on 2026-05-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('vat_id', models.CharField(blank=True, max_length=64)),
                ('tax_code', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('country_code', models.CharField(default='IT', max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'vat_id'), name='customers_customer_name_vat_uniq')],
            },
        ),
    ]
