# Generated by Django 6.0.2 on 2026-03-03 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('service_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External service',
                'verbose_name_plural': 'External services',
                'db_table': 'services_external_service',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value_encrypted', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='services.externalservice')),
            ],
            options={
                'verbose_name': 'Service credential',
                'verbose_name_plural': 'Service credentials',
                'db_table': 'services_service_credential',
                'ordering': ['external_service', 'name'],
            },
        ),
    ]
