# Generated by Django 6.0.2 on 2026-05-06 12:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('documents', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(help_text='Invoice number from document', max_length=100)),
                ('invoice_date', models.DateField(help_text='Date when invoice was issued')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('payment_date', models.DateField(blank=True, help_text='Actual payment date', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total invoice amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='EUR', help_text='Currency code (ISO 4217)', max_length=3)),
                ('converted_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to base currency', max_digits=12, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Exchange rate used for conversion', max_digits=8, null=True)),
                ('vat_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='VAT percentage applied', max_digits=5, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, help_text='VAT amount', max_digits=12, null=True)),
                ('taxable_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount before VAT', max_digits=12, null=True)),
                ('original_filename', models.CharField(help_text='Original PDF filename', max_length=255)),
                ('file_path', models.CharField(help_text='Path to PDF file', max_length=500)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending Extraction'), ('extracted', 'Data Extracted'), ('review', 'Needs Manual Review'), ('completed', 'Processing Completed'), ('error', 'Processing Error')], default='pending', help_text='Processing status', max_length=20)),
                ('needs_manual_review', models.BooleanField(default=False, help_text='Whether manual review is required')),
                ('extraction_errors', models.TextField(blank=True, help_text='Any errors encountered during processing')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('invoice_type', models.CharField(choices=[('received', 'Received Invoice'), ('emitted', 'Emitted Invoice')], default='received', help_text='Type of invoice: received (from vendor) or emitted (to customer)', max_length=20)),
                ('customer', models.ForeignKey(blank=True, help_text='Customer who received the invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='customers.customer')),
                ('document_file', models.ForeignKey(blank=True, help_text='Source document file this invoice was created from (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='documents.documentfile')),
                ('payment_method', models.ForeignKey(blank=True, help_text='Payment method used', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.paymentmethod')),
                ('vendor', models.ForeignKey(blank=True, help_text='Vendor who issued the invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_text', models.TextField(blank=True, help_text='Raw text extracted from PDF')),
                ('raw_extracted_data', models.JSONField(default=dict, help_text='Raw JSON data extracted by LLM')),
                ('validated_data', models.JSONField(blank=True, default=dict, help_text='Validated and cleaned data', null=True)),
                ('extraction_method', models.CharField(default='llm', help_text='Method used for extraction (llm, regex, manual)', max_length=50)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence score (0-100) for extraction quality', max_digits=5, null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When extraction was completed', null=True)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('last_error', models.TextField(blank=True, help_text='Last error message')),
                ('invoice', models.OneToOneField(help_text='Associated invoice', on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Extraction',
                'verbose_name_plural': 'Invoice Extractions',
            },
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Template name/identifier', max_length=255)),
                ('template_type', models.CharField(choices=[('received', 'Received Invoice Template'), ('emitted', 'Emitted Invoice Template')], default='received', help_text='Type of template: received (from vendor) or emitted (to customer)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of the template')),
                ('spatial_data', models.JSONField(default=dict, help_text="Spatial information about field locations. Format: {'field_name': {'region': 'top_left', 'coordinates': {...}, 'patterns': [...]}}")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default template for the vendor/user')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this template has been used')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When this template was last used', null=True)),
                ('sample_invoice', models.ForeignKey(blank=True, help_text='Reference invoice used to create this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_samples', to='invoices.invoice')),
                ('user', models.ForeignKey(blank=True, help_text='User/company this template belongs to (for emitted invoices)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_templates', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('vendor', models.ForeignKey(blank=True, help_text='Vendor this template belongs to (for received invoices)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_templates', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Invoice Template',
                'verbose_name_plural': 'Invoice Templates',
                'ordering': ['-is_default', '-usage_count', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Invoice template used for extraction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.invoicetemplate'),
        ),
        migrations.AddConstraint(
            model_name='invoicetemplate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', True), ('vendor__isnull', False)), models.Q(('user__isnull', False), ('vendor__isnull', True)), _connector='OR'), name='template_must_have_vendor_or_user'),
        ),
    ]
