# Generated by Django 6.0.2 on 2026-05-11 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bic',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='invoice',
            name='classification_hints',
            field=models.JSONField(blank=True, default=dict, help_text='Optional upload-time hints (invoice_type, vendor_id, currency, notes, …) for extraction.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_vat_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_kind',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit note'), ('proforma', 'Pro forma'), ('other', 'Other')], default='invoice', help_text='Kind of source document', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='iban',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_override',
            field=models.BooleanField(default=False, help_text='When true, treat invoice as paid without full payment transaction coverage.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_vat_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='invoice',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_invoices', to=settings.AUTH_USER_MODEL, db_constraint=False),
        ),
        migrations.AddField(
            model_name='invoiceextraction',
            name='field_confidence',
            field=models.JSONField(blank=True, default=dict, help_text='Per-field confidence scores (0-1), keyed by field name'),
        ),
        migrations.AddField(
            model_name='invoiceextraction',
            name='llm_model_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='invoiceextraction',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
