# Generated by Django 6.0.2 on 2026-05-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_upload_hints_and_extraction_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='file_path',
            field=models.CharField(blank=True, help_text='Path to PDF file', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original PDF filename', max_length=255, null=True),
        ),
    ]
