# Generated by Django 6.0.2 on 2026-05-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('security_audit', 'Security audit'), ('performance', 'Performance'), ('resources', 'Resource consumption')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('schedule', models.CharField(blank=True, help_text='Cron expression or human-readable interval.', max_length=255)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Planned check',
                'verbose_name_plural': 'Planned checks',
                'db_table': 'checks_planned_check',
                'ordering': ['next_run_at', 'name'],
            },
        ),
    ]
