# Generated by Django 6.0.2 on 2026-05-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('knowledge', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Entity link',
                'verbose_name_plural': 'Entity links',
                'db_table': 'knowledge_entity_link',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.PositiveIntegerField()),
                ('target_object_id', models.PositiveIntegerField()),
                ('relation_type', models.CharField(choices=[('made_of', 'Made of'), ('depends_on', 'Depends on'), ('tags', 'Tags'), ('related', 'Related'), ('uses', 'Uses')], default='related', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_relations_out', to='contenttypes.contenttype')),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_relations_in', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Knowledge relation',
                'verbose_name_plural': 'Knowledge relations',
                'db_table': 'knowledge_relation',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('url', 'URL'), ('pdf', 'PDF'), ('import', 'Import')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge source',
                'verbose_name_plural': 'Knowledge sources',
                'db_table': 'knowledge_source',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='article',
            name='article_kind',
            field=models.CharField(choices=[('article', 'Article'), ('procedure', 'Procedure'), ('cheatsheet', 'Cheatsheet'), ('pattern', 'Pattern'), ('other', 'Other')], default='article', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='articles', to='topics.topic'),
        ),
        migrations.AddField(
            model_name='entitylink',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='knowledge.article'),
        ),
        migrations.AddField(
            model_name='entitylink',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='sources', to='knowledge.article'),
        ),
        migrations.AlterUniqueTogether(
            name='entitylink',
            unique_together={('article', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='knowledgerelation',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='knowledge_r_source__1a5353_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgerelation',
            index=models.Index(fields=['target_content_type', 'target_object_id'], name='knowledge_r_target__06de7f_idx'),
        ),
    ]
