# Generated by Django 6.0.2 on 2026-03-03 13:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal entry',
                'verbose_name_plural': 'Journal entries',
                'db_table': 'accounting_journal_entry',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Journal entry line',
                'verbose_name_plural': 'Journal entry lines',
                'db_table': 'accounting_journal_entry_line',
            },
        ),
    ]
