# Generated by Django 6.0.2 on 2026-05-06 12:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodAccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('ending_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Reported balance at end of period (from bank/cash statement).', max_digits=14)),
                ('computed_flow', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Auto: signed sum of transactions in this period for this account.', max_digits=14)),
                ('computed_ending', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Auto: starting_balance + computed_flow.', max_digits=14)),
                ('discrepancy', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Auto: ending_balance - computed_ending. Zero means balanced.', max_digits=14)),
                ('is_balanced', models.BooleanField(default=False)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Period account balance',
                'verbose_name_plural': 'Period account balances',
                'db_table': 'accounting_period_account_balance',
                'ordering': ['period', 'account'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('locked', 'Locked')], default='open', max_length=16)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiscal period',
                'verbose_name_plural': 'Fiscal periods',
                'db_table': 'accounting_fiscal_period',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='AccountingExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('daybook', 'Daybook'), ('income_statement', 'Income statement'), ('balance', 'Balance'), ('full_package', 'Full monthly package')], max_length=32)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('parameters_json', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_exports', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='accounting.fiscalperiod')),
            ],
            options={
                'verbose_name': 'Accounting export',
                'verbose_name_plural': 'Accounting exports',
                'db_table': 'accounting_export',
                'ordering': ['-generated_at'],
            },
        ),
    ]
