# Generated by Django 6.0.2 on 2026-05-06 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodaccountbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_balances', to='money.account'),
        ),
        migrations.AddField(
            model_name='periodaccountbalance',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='accounting.fiscalperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalperiod',
            unique_together={('year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='periodaccountbalance',
            unique_together={('period', 'account')},
        ),
    ]
