# Generated by Django 6.0.2 on 2026-05-07 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Daybook',
            fields=[
            ],
            options={
                'verbose_name': 'Daybook',
                'verbose_name_plural': 'Daybooks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.fiscalperiod',),
        ),
        migrations.AddField(
            model_name='periodaccountbalance',
            name='opening_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodaccountbalance',
            name='opening_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_period_openings', to=settings.AUTH_USER_MODEL, db_constraint=False),
        ),
    ]
