# Generated by Django 6.0.2 on 2026-05-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_period_account_balance_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingexport',
            name='kind',
            field=models.CharField(choices=[('daybook', 'Daybook'), ('income_statement', 'Income statement'), ('balance', 'Balance'), ('full_package', 'Full monthly package'), ('full_year_package', 'Full yearly package')], max_length=32),
        ),
    ]
