# Generated by Django 6.0.2 on 2026-05-06 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Folder name', max_length=255)),
                ('path', models.CharField(help_text='Full path to folder', max_length=500, unique=True)),
                ('description', models.TextField(blank=True, help_text='Folder description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether folder is being monitored')),
                ('auto_process', models.BooleanField(default=True, help_text='Whether to automatically process new files')),
            ],
            options={
                'verbose_name': 'Document Folder',
                'verbose_name_plural': 'Document Folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_path', models.CharField(help_text='Full path to file', max_length=500)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_hash', models.CharField(blank=True, help_text='File hash for duplicate detection', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Currently Processing'), ('processed', 'Successfully Processed'), ('error', 'Processing Error'), ('skipped', 'Skipped')], default='pending', help_text='Processing status', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('file_type', models.CharField(default='pdf', help_text='File type/extension', max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='When file was first detected')),
                ('folder', models.ForeignKey(help_text='Parent folder', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.documentfolder')),
            ],
            options={
                'verbose_name': 'Document File',
                'verbose_name_plural': 'Document Files',
                'ordering': ['-upload_date'],
                'unique_together': {('folder', 'filename')},
            },
        ),
    ]
