# Generated by Django 6.0.2 on 2026-05-12 09:37

import apps.documents.storage
import django.core.validators
from django.db import migrations, models


def backfill_document_file_from_legacy_path(apps, schema_editor):
    DocumentFile = apps.get_model("documents", "DocumentFile")
    from django.conf import settings
    from django.core.files import File

    import os

    for doc in DocumentFile.objects.all().iterator(chunk_size=200):
        if getattr(doc, "file", None):
            name = getattr(doc.file, "name", "") or ""
            if name.strip():
                continue
        fp = (doc.file_path or "").strip()
        if not fp:
            continue
        abs_path = fp if os.path.isabs(fp) else os.path.join(str(settings.MEDIA_ROOT), fp)
        if not os.path.isfile(abs_path):
            continue
        basename = os.path.basename(abs_path)
        try:
            with open(abs_path, "rb") as fh:
                doc.file.save(basename, File(fh), save=False)
            doc.file_path = ""
            doc.save()
        except OSError:
            continue


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfile",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Stored file under MEDIA (preferred).",
                max_length=512,
                null=True,
                upload_to=apps.documents.storage.document_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "png", "jpg", "jpeg", "tif", "tiff", "csv"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="file_path",
            field=models.CharField(
                blank=True,
                help_text="Legacy absolute or MEDIA-relative path; prefer ``file`` for new rows.",
                max_length=500,
            ),
        ),
        migrations.RunPython(backfill_document_file_from_legacy_path, noop_reverse),
    ]
