# Generated by Django 6.0.2 on 2026-05-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfolder',
            name='path',
            field=models.CharField(help_text='Path relative to MEDIA_ROOT (e.g. invoices/received). Not an absolute filesystem path.', max_length=500, unique=True),
        ),
    ]
