# Generated by Django 6.0.2 on 2026-05-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentfile_processing_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='processing_task_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Last Celery task id for invoice extraction (see django_celery_results).', max_length=255),
        ),
    ]
