# Generated by Django 6.0.2 on 2026-05-11 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('trading_name', models.CharField(blank=True, max_length=255)),
                ('vat_id', models.CharField(blank=True, max_length=64)),
                ('tax_code', models.CharField(blank=True, max_length=64)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('country_code', models.CharField(default='IT', max_length=2)),
                ('trading_aliases', models.JSONField(blank=True, default=list)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('website', models.URLField(blank=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant company profile',
                'verbose_name_plural': 'Tenant company profiles',
            },
        ),
    ]
