# Generated by Django 6.0.2 on 2026-05-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('environment', models.CharField(choices=[('prod', 'Production'), ('staging', 'Staging'), ('dev', 'Development'), ('other', 'Other')], default='prod', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Architecture profile',
                'verbose_name_plural': 'Architecture profiles',
                'db_table': 'architecture_profile',
                'ordering': ['project', '-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArchitectureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('component_type', models.CharField(choices=[('database', 'Database'), ('cache', 'Cache'), ('search_engine', 'Search engine'), ('object_storage', 'Object storage'), ('data_warehouse', 'Data warehouse'), ('message_broker', 'Message broker'), ('event_bus', 'Event bus'), ('task_queue', 'Task queue'), ('load_balancer', 'Load balancer'), ('reverse_proxy', 'Reverse proxy'), ('api_gateway', 'API gateway'), ('cdn', 'CDN'), ('dns', 'DNS'), ('firewall', 'Firewall'), ('vpn', 'VPN'), ('application_server', 'Application server'), ('container_runtime', 'Container runtime'), ('orchestrator', 'Orchestrator'), ('serverless', 'Serverless'), ('vm', 'Virtual machine'), ('metrics', 'Metrics'), ('logging', 'Logging'), ('tracing', 'Tracing'), ('alerting', 'Alerting'), ('secrets_manager', 'Secrets manager'), ('certificate_store', 'Certificate store'), ('waf', 'WAF'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('engine', models.CharField(blank=True, max_length=100)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('deprecated', 'Deprecated')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='architecture_components', to='systems.system')),
            ],
            options={
                'verbose_name': 'Architecture component',
                'verbose_name_plural': 'Architecture components',
                'db_table': 'architecture_component',
                'ordering': ['profile', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArchitectureConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('depends_on', 'Depends on'), ('routes_to', 'Routes to'), ('replicates_to', 'Replicates to'), ('reads_from', 'Reads from'), ('writes_to', 'Writes to'), ('publishes_to', 'Publishes to'), ('subscribes_to', 'Subscribes to')], default='depends_on', max_length=20)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='architecture.architecturecomponent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='architecture.architecturecomponent')),
            ],
            options={
                'verbose_name': 'Architecture connection',
                'verbose_name_plural': 'Architecture connections',
                'db_table': 'architecture_connection',
            },
        ),
    ]
