# Generated by Django 6.0.2 on 2026-05-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('architecture', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectureprofile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architecture_profiles', to='projects.project'),
        ),
        migrations.AddField(
            model_name='architecturecomponent',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='architecture.architectureprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='architecturecomponent',
            unique_together={('profile', 'slug')},
        ),
    ]
