# Generated by Django 6.0.2 on 2026-05-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_seed_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default bank/cash account for automated postings (e.g. invoice payments).'),
        ),
    ]
