# Generated by Django 6.0.2 on 2026-05-12 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_add_default_flags'),
        ('vendors', '0003_alter_paymentmethod_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Payment method used', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.paymentmethod'),
        ),
    ]
