# Generated by Django 6.0.2 on 2026-05-13 08:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models


def backfill_allocations(apps, schema_editor):
    Transaction = apps.get_model("money", "Transaction")
    InvoiceSettlementAllocation = apps.get_model("money", "InvoiceSettlementAllocation")
    Invoice = apps.get_model("invoices", "Invoice")

    for tx in Transaction.objects.exclude(invoice_id__isnull=True).iterator(chunk_size=500):
        inv = Invoice.objects.filter(pk=tx.invoice_id).first()
        if inv is None:
            continue
        amt_s = tx.amount
        amt_i = tx.amount if inv.currency_id == tx.currency_id else tx.amount
        InvoiceSettlementAllocation.objects.create(
            transaction_id=tx.pk,
            invoice_id=inv.pk,
            amount_settlement=amt_s,
            amount_invoice=amt_i,
        )


def reverse_backfill(apps, schema_editor):
    InvoiceSettlementAllocation = apps.get_model("money", "InvoiceSettlementAllocation")
    InvoiceSettlementAllocation.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_currency_fk'),
        ('money', '0004_transaction_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettlementAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_settlement', models.DecimalField(decimal_places=2, help_text="Portion of this transaction in the transaction's currency (e.g. EUR bank line).", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount_invoice', models.DecimalField(decimal_places=2, help_text="Same slice in the invoice's currency (for outstanding / audit).", max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=8, help_text='Optional rate used between invoice currency and settlement currency.', max_digits=18, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Invoice settlement allocation',
                'verbose_name_plural': 'Invoice settlement allocations',
                'db_table': 'money_invoice_settlement_allocation',
            },
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='money_trans_invoice_aa6611_idx',
        ),
        migrations.AddField(
            model_name='invoicesettlementallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_allocations', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='invoicesettlementallocation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_allocations', to='money.transaction'),
        ),
        migrations.RunPython(backfill_allocations, reverse_backfill),
        migrations.RemoveField(
            model_name='transaction',
            name='invoice',
        ),
        migrations.AddIndex(
            model_name='invoicesettlementallocation',
            index=models.Index(fields=['transaction'], name='money_invoi_transac_8100b0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicesettlementallocation',
            index=models.Index(fields=['invoice'], name='money_invoi_invoice_7a8fe4_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoicesettlementallocation',
            constraint=models.UniqueConstraint(fields=('transaction', 'invoice'), name='uniq_settlement_tx_invoice'),
        ),
    ]
