# Generated by Django 6.0.2 on 2026-05-13 10:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_currency_fk'),
        ('money', '0005_invoice_settlement_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesettlementallocation',
            name='amount_invoice',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Slice in invoice currency when linked to an invoice; empty for fee-only lines.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='invoicesettlementallocation',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice this slice settles; leave empty for a fee/FX/rounding line.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlement_allocations', to='invoices.invoice'),
        ),
    ]
