# Generated by Django 6.0.2 on 2026-05-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0002_deadline_content_type_deadline_object_id'),
        ('money', '0006_invoice_settlement_fee_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('period', models.CharField(choices=[('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year')], default='month', max_length=20)),
                ('period_start', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('alert_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Optional percentage (0-100) at which to alert.', max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'db_table': 'money_budget',
                'ordering': ['-period_start', 'name'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='deadline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='deadlines.deadline'),
        ),
    ]
