# Generated by Django 6.0.2 on 2026-05-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_budget_transaction_deadline'),
        ('products', '0002_remove_product_status_product_docs_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='product_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='products.productlicense'),
        ),
    ]
