"""
Django settings for operational project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
except ImportError:
    pass


def _env_str(name: str, default: str) -> str:
    raw = os.getenv(name)
    if raw is None:
        return default
    raw = raw.strip()
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in ('"', "'"):
        raw = raw[1:-1]
    return raw


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dn^p14h8f08i0!+tr^a74sn-n@-y(am2qhmy2@x01y@!w$g^u!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

SHARED_APPS = [
    "django_cotton",
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "unfold.contrib.import_export",
    "import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "unfold.contrib.location_field",
    "unfold.contrib.constance",
    "django.contrib.admin",
    "django.contrib.auth",
    "tenant_users.permissions",
    "tenant_users.tenants",
    "django_tenants",
    "apps.tenants",
    "apps.users",
    "apps.subscriptions",
    "apps.core",
    "apps.ai",
    "apps.api",
    "apps.integrations",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_results",
]

TENANT_APPS = [
    # Required in tenant schemas: GenericForeignKey (contenttypes), permissions (auth).
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "tenant_users.permissions",
    "apps.projects",
    "apps.services",
    "apps.dashboard",
    "apps.plans",
    "apps.milestones",
    "apps.products",
    "apps.systems",
    "apps.parts",
    "apps.topics",
    "apps.knowledge",
    "apps.tasks",
    "apps.deadlines",
    "apps.money",
    "apps.accounting",
    "apps.customers",
    "apps.vendors",
    "apps.documents",
    "apps.invoices",
    "apps.organizations",
    "rest_framework",
    "django_filters",
    "django_drf_filepond",
    "apps.files",
    "apps.workflows",
    "apps.architecture",
    "apps.stack",
    "apps.issues",
    "apps.testing",
    "apps.operations",
    "apps.checks",
    "apps.solutions",
]

INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

TENANT_MODEL = "tenants.Tenant"  # app.Model

TENANT_DOMAIN_MODEL = "tenants.Domain"  # app.Model

# UserTenantPermissions.profile → public-schema TenantUser (no cross-schema FK).
MIGRATION_MODULES = {
    "permissions": "operational.permissions_migrations",
}

# django-import-export: wrap each import in a single DB transaction so a
# partial XLS upload never leaves accounting data half-imported.
IMPORT_EXPORT_USE_TRANSACTIONS = True


MIDDLEWARE = [
    "django_tenants.middleware.main.TenantMainMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "tenant_users.tenants.middleware.TenantAccessMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'operational.urls'

UI_TEMPLATES = os.path.join(BASE_DIR, "templates")

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [UI_TEMPLATES],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'operational.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

## SQLite database settings
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

## Tenants aware database settings
DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": "operational",
        "USER": "tobia",
        "PASSWORD": "",
        "HOST": "localhost",
        "PORT": "5432",
        # ..
    }
}

DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)

AUTH_USER_MODEL = "users.TenantUser"

AUTHENTICATION_BACKENDS = (
    "tenant_users.permissions.backend.UserBackend",
    "django.contrib.auth.backends.ModelBackend",
)

TENANT_USERS_DOMAIN = os.getenv("TENANT_USERS_DOMAIN", "localhost")

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Invoice uploads (single PDF via FilePond, ZIP batch)
INVOICE_MAX_UPLOAD_BYTES = int(os.getenv("INVOICE_MAX_UPLOAD_BYTES", str(25 * 1024 * 1024)))
INVOICE_ZIP_MAX_BYTES = int(os.getenv("INVOICE_ZIP_MAX_BYTES", str(50 * 1024 * 1024)))
INVOICE_ZIP_MAX_FILES = int(os.getenv("INVOICE_ZIP_MAX_FILES", "200"))


def _env_truthy(name: str, *, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in ("1", "true", "yes", "on")


# Celery: one global broker (e.g. Redis). django-tenants schema is not chosen by
# broker URL; ``tenant-schemas-celery`` stamps ``_schema_name`` on task headers at
# publish time and switches ``connection`` in the worker (see operational/celery.py).
CELERY_BROKER_URL = _env_str("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = _env_str("CELERY_RESULT_BACKEND", "django-db")
CELERY_TASK_ALWAYS_EAGER = _env_truthy(
    "CELERY_TASK_ALWAYS_EAGER",
    default=False,
)
CELERY_RESULT_EXTENDED = True
# Persist STARTED in django_celery_results as soon as a worker picks up the task
# (otherwise the TaskResult row often appears only after SUCCESS/FAILURE).
CELERY_TASK_TRACK_STARTED = _env_truthy(
    "CELERY_TASK_TRACK_STARTED",
    default=True,
)

# django-drf-filepond: temp + stored paths must live under BASE_DIR unless
# DJANGO_DRF_FILEPOND_ALLOW_EXTERNAL_UPLOAD_DIR is True.
FILEPOND_UPLOAD_TMP = BASE_DIR / "filepond_tmp"
FILEPOND_FILE_STORE = BASE_DIR / "filepond_store"
DJANGO_DRF_FILEPOND_UPLOAD_TMP = str(FILEPOND_UPLOAD_TMP)
DJANGO_DRF_FILEPOND_FILE_STORE_PATH = str(FILEPOND_FILE_STORE)
DJANGO_DRF_FILEPOND_PERMISSION_CLASSES = {
    "POST_PROCESS": ["rest_framework.permissions.IsAuthenticated"],
    "DELETE_REVERT": ["rest_framework.permissions.IsAuthenticated"],
    "PATCH_PATCH": ["rest_framework.permissions.IsAuthenticated"],
    "GET_LOAD": ["rest_framework.permissions.IsAuthenticated"],
    "GET_RESTORE": ["rest_framework.permissions.IsAuthenticated"],
    "GET_FETCH": ["rest_framework.permissions.IsAuthenticated"],
}

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
}

# Ollama: ``OLLAMA_MODEL`` must match a tag from ``ollama list`` (e.g. llama3.2, llama3.2:3b).
# If ``OLLAMA_URL`` is unset, ``OLLAMA_HOST`` (e.g. http://127.0.0.1:11434) is used to build /api/generate.
if (os.getenv("OLLAMA_URL") or "").strip():
    OLLAMA_URL = _env_str("OLLAMA_URL", "http://127.0.0.1:11434/api/generate")
else:
    _ollama_host = _env_str("OLLAMA_HOST", "http://127.0.0.1:11434").rstrip("/")
    OLLAMA_URL = f"{_ollama_host}/api/generate"
OLLAMA_MODEL = _env_str("OLLAMA_MODEL", "llama3.2")
OLLAMA_TIMEOUT = int(os.getenv("OLLAMA_TIMEOUT", "120"))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
    "filters": {
        "tenant_context": {"()": "django_tenants.log.TenantContextFilter"},
    },
    "formatters": {
        "tenant_context": {
            "format": "[%(schema_name)s:%(domain_url)s] "
            "%(levelname)-7s %(asctime)s %(message)s",
        },
    },
}

ENABLE_DEBUG_TOOLBAR = DEBUG and "test" not in sys.argv
if ENABLE_DEBUG_TOOLBAR:
    INSTALLED_APPS += [
        "debug_toolbar",
    ]
    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ]
    # Customize the config to support turbo and htmx boosting.
    DEBUG_TOOLBAR_CONFIG = {"ROOT_TAG_EXTRA_ATTRS": "data-turbo-permanent hx-preserve"}

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

UNFOLD = {
    "SITE_TITLE": "Operational Admin",
    "SITE_HEADER": "Operational",
    "SITE_SUBHEADER": "Control Center",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": "apps.core.admin_navigation.sidebar_show_all_applications",
        "navigation": "apps.core.admin_navigation.get_sidebar_navigation",
    },
    "STYLES": [
        lambda request: "/static/css/unfold-admin.css",
    ],
}
