# Generated by Django 6.0.2 on 2026-05-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_type',
            field=models.CharField(choices=[('token', 'Token'), ('account', 'Account'), ('license', 'License'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('value_masked', models.CharField(blank=True, max_length=100)),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('environment', models.CharField(blank=True, max_length=50)),
                ('last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('next_rotation_due', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'db_table': 'parts_api_key',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('credential_kind', models.CharField(choices=[('api_secret', 'API secret'), ('oauth', 'OAuth'), ('password', 'Password'), ('cert', 'Certificate'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('value_masked', models.CharField(blank=True, max_length=100)),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('environment', models.CharField(blank=True, max_length=50)),
                ('last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('next_rotation_due', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
                'db_table': 'parts_credential',
                'ordering': ['name'],
            },
        ),
    ]
