# Generated by Django 6.0.2 on 2026-05-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('architecture', '0002_initial'),
        ('knowledge', '0002_entitylink_knowledgerelation_knowledgesource_and_more'),
        ('projects', '0001_initial'),
        ('systems', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('deprecated', 'Deprecated')], default='proposed', max_length=20)),
                ('problem_summary', models.TextField(blank=True)),
                ('decision_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('architecture_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='architecture.architectureprofile')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to='knowledge.article')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='projects.project')),
                ('systems', models.ManyToManyField(blank=True, related_name='solutions', to='systems.system')),
                ('topics', models.ManyToManyField(blank=True, related_name='solutions', to='topics.topic')),
            ],
            options={
                'verbose_name': 'Solution',
                'verbose_name_plural': 'Solutions',
                'db_table': 'solutions_solution',
                'ordering': ['-updated_at'],
            },
        ),
    ]
