# Generated by Django 6.0.2 on 2026-05-26 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('systems', '0002_system_dashboard_url_system_depends_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('e2e', 'End-to-end'), ('integration', 'Integration'), ('smoke', 'Smoke')], default='manual', max_length=20)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scenarios', to='projects.project')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_scenarios', to='systems.system')),
            ],
            options={
                'verbose_name': 'Test scenario',
                'verbose_name_plural': 'Test scenarios',
                'db_table': 'testing_test_scenario',
                'ordering': ['project', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('skip', 'Skip'), ('blocked', 'Blocked')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_runs', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='testing.testscenario')),
            ],
            options={
                'verbose_name': 'Test run',
                'verbose_name_plural': 'Test runs',
                'db_table': 'testing_test_run',
                'ordering': ['-run_at'],
            },
        ),
    ]
