# Generated by Django 6.0.2 on 2026-05-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('overall_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('integration', 'Integration'), ('agent', 'Agent')], default='manual', max_length=20)),
            ],
            options={
                'verbose_name': 'Operational snapshot',
                'verbose_name_plural': 'Operational snapshots',
                'db_table': 'operations_operational_snapshot',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
