# Generated by Django 6.0.2 on 2026-05-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('check', 'Check'), ('other', 'Other')], max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name for payment method', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether payment method is active')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Vendor company name', max_length=255)),
                ('vat_id', models.CharField(blank=True, help_text='VAT identification number', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Complete vendor address')),
                ('country_code', models.CharField(default='IT', help_text='ISO country code', max_length=2)),
                ('email', models.EmailField(blank=True, help_text='Vendor contact email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Vendor contact phone', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether vendor is active')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
    ]
