# Generated by Django 6.0.2 on 2026-05-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Preferred method when creating transactions from invoices without explicit choice.'),
        ),
    ]
