# Generated by Django 6.0.2 on 2026-05-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_add_default_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('f24', 'F24'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('check', 'Check'), ('other', 'Other')], max_length=20, unique=True),
        ),
    ]
