# Generated by Django 6.0.2 on 2026-03-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('system_type', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('multi_tenant', 'Multi-tenant system'), ('authentication', 'Authentication system'), ('permissions', 'Permissions system'), ('background_tasks', 'Background tasks system'), ('observability', 'Observability system'), ('api_client', 'API client system'), ('mcp_server', 'MCP server system'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('environment', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
                'db_table': 'systems_system',
                'ordering': ['name'],
            },
        ),
    ]
