# Generated by Django 6.0.2 on 2026-05-26 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='dashboard_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='system',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='depended_on_by', to='systems.system'),
        ),
        migrations.AddField(
            model_name='system',
            name='docs_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='system',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='system',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_systems', to=settings.AUTH_USER_MODEL, db_constraint=False),
        ),
        migrations.AddField(
            model_name='system',
            name='repo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='system',
            name='scope',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='system',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='system',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='systems', to='topics.topic'),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_type',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure'), ('multi_tenant', 'Multi-tenant system'), ('authentication', 'Authentication system'), ('permissions', 'Permissions system'), ('background_tasks', 'Background tasks system'), ('observability', 'Observability system'), ('api_client', 'API client system'), ('mcp_server', 'MCP server system'), ('api', 'API'), ('integration', 'Integration layer'), ('data_store', 'Data store'), ('messaging', 'Messaging'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
