# Generated by Django 6.0.2 on 2026-05-26 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('kind', models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('library', 'Library'), ('runtime', 'Runtime'), ('tool', 'Tool'), ('pattern', 'Pattern')], default='library', max_length=20)),
                ('version_label', models.CharField(blank=True, max_length=100)),
                ('homepage_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'db_table': 'stack_technology',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('role', models.CharField(blank=True, max_length=100)),
                ('version_constraint', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='stack.technology')),
            ],
            options={
                'verbose_name': 'Technology usage',
                'verbose_name_plural': 'Technology usages',
                'db_table': 'stack_technology_usage',
                'ordering': ['technology'],
            },
        ),
    ]
