# Generated by Django 6.0.2 on 2026-05-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'default_permissions': (), 'ordering': ['-updated_at'], 'verbose_name': 'Workflow', 'verbose_name_plural': 'Workflows'},
        ),
    ]
