# Generated by Django 6.0.2 on 2026-05-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_workflow_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Workflow', 'verbose_name_plural': 'Workflows'},
        ),
        migrations.AddField(
            model_name='workflow',
            name='category',
            field=models.CharField(choices=[('knowledge', 'Knowledge mapping'), ('automation', 'Automation pipeline'), ('procedure', 'Procedure / SOP'), ('general', 'General')], db_index=True, default='general', max_length=32),
        ),
    ]
