# Generated by Django 6.0.2 on 2026-05-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_ensure_workflow_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-updated_at'], 'verbose_name': 'Workflow', 'verbose_name_plural': 'Workflows'},
        ),
    ]
