# Generated by Django 6.0.2 on 2026-05-14 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflows', '0005_workflow_default_permissions_explicit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowNodeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(db_index=True, max_length=128)),
                ('object_id', models.CharField(max_length=64)),
                ('role', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_links', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Workflow node link',
                'verbose_name_plural': 'Workflow node links',
                'db_table': 'workflows_workflownodelink',
                'ordering': ['-created_at'],
            },
        ),
    ]
