# Generated by Django 6.0.2 on 2026-05-06 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('vat_id', models.CharField(blank=True, max_length=64)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('legal_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('country_code', models.CharField(default='IT', max_length=2)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
